
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mapit_user
      POSTGRES_PASSWORD: mapit_password
      POSTGRES_DB: mapit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mapit_user -d mapit_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mapit-network

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://mapit_user:mapit_password@db:5432/mapit_db
      SECRET_KEY: dev-secret-key-change-in-production
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      FRONTEND_URL: http://localhost:5173
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mapit-network

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - mapit-network

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha
    depends_on:
      - db
    networks:
      - mapit-network

volumes:
  postgres_data:

networks:
  mapit-network:
    driver: bridge

